version: "3"
services:
  postgresql:
    build:
      context: ./db-migration
      dockerfile: Dockerfile
    container_name: atm_db
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - DB_URL=${DB_URL}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "--dbname=atm", "--username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build: service
    container_name: atm_server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgresql
    links:
      - postgresql
