version: "3"
services:
  postgresql:
    build:
      context: ./db-migration
      dockerfile: Dockerfile
    container_name: atm_db
    environment:
      - POSTGRESQL_PASSWORD=mypass
      - POSTGRESQL_DATABASE=atm
      - DB_URL=postgres://postgres:mypass@localhost:5432/atm?sslmode=disable
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "--dbname=atm", "--username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build: service
    container_name: atm_server
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=atm
      - DB_USER=postgres
      - DB_PASS=mypass
      - JWT_SECRET=mysecret
    depends_on:
      - postgresql
    links:
      - postgresql
